In [1]:
import pandas as pd 
import numpy as np
import pyarrow
from pathlib import Path

In [2]:
path = Path.cwd().parent
print(path)

/home/alvaro/PROJECTS/poblet

In [3]:
df_youtube = pd.read_csv(path / 'data' / 'creadores_youtube.csv')

df_youtube.head()

                                       creador                    nick_youtube
0  ACICOM. Associació Ciutadania i Comunicació                    CANAL-ACICOM
1            Acadèmia Valenciana de la Llengua  academiavalencianadelallen1454
2             Acció Cultural del País Valencià                 AccioCulturalPV
3                                    Alvamoll7        UCApur1OXkh3hygrpsz569Fg
4         De mica en mica. Dra. Aina Monferrer             AinaMonferrerPalmer

In [9]:
df_youtube[df_youtube["creador"] == "lletivi_22"]

Empty DataFrame
Columns: [creador, nick_youtube]
Index: []

In [ ]:
len(df_youtube)

93